# Generated by Django 3.2.7 on 2021-10-19 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("coped_resources", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="resource",
            name="couchdb_name_idx",
        ),
        migrations.RemoveField(
            model_name="resource",
            name="couchdb_name",
        ),
        migrations.AddField(
            model_name="resourcetype",
            name="couchdb_name",
            field=models.ForeignKey(
                help_text="Which CouchDB database is the resource from?",
                on_delete=django.db.models.deletion.PROTECT,
                to="coped_resources.couchdbname",
            ),
            preserve_default=False,
        ),
    ]
