# Generated by Django 3.2.7 on 2021-10-19 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coped_resources', '0002_auto_20211019_0803'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='resourcetype',
            unique_together={('description', 'couchdb_name')},
        ),
    ]
