# Generated by Django 3.2.7 on 2021-10-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coped_resources', '0003_alter_resourcetype_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcetype',
            name='item_type',
            field=models.CharField(blank=True, help_text="What is the 'item_type' in the CouchDB document meta data?", max_length=128),
        ),
        migrations.AlterField(
            model_name='resourcetype',
            name='description',
            field=models.CharField(help_text='What type of resource is this?', max_length=128),
        ),
    ]
