# Generated by Django 3.2.7 on 2021-10-19 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coped_resources', '0004_auto_20211019_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcetype',
            name='item_type',
            field=models.CharField(help_text="What is the 'item_type' in the CouchDB document meta data?", max_length=128),
        ),
    ]
