version: '3'

services:

  web:
    volumes:
      # - ./dashboards:${VOILA_NOTEBOOK_DIR:?}
      - ./services/web:/app
    environment:
      DEBUG: 1
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"

  db:
    volumes:
      - /var/tmp/coped/postgresql/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  couch:
    volumes:
      - /var/tmp/coped/couchdb/data:/opt/couchdb/data
    ports:
      - "5984:5984"

  # voila:
  #   build: ./services/voila
  #   volumes:
  #     - type: bind
  #       source: ./dashboards
  #       target: ${VOILA_NOTEBOOK_DIR:?}
  #       read_only: true
  #   ports:
  #     - "8866:8866"

  elasticsearch:
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - /var/tmp/coped/elasticsearch/data:/usr/share/elasticsearch/data
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"

  # logstash:
  #   ports:
  #     - "5044:5044"
  #     - "5000:5000/tcp"
  #     - "5000:5000/udp"
  #     - "9600:9600"
  #   environment:
  #     LS_JAVA_OPTS: "-Xmx256m -Xms256m"

  # kibana:
  #   ports:
  #     - "5601:5601"

  tasks:
    environment:
      DEBUG: 1
    volumes:
      - ./tasks:/tasks:cached
