services:

  ##########################
  ##  ALWAYS-ON SERVICES  ##
  ##########################
  web:
    build: ./services/web
    container_name: coped_web
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:${DJANGO_STATIC_ROOT:?}
    expose:
      - 8000
    environment:
      DEBUG: 0
      SECRET_KEY: ${DJANGO_SECRET_KEY:?}
      STATIC_ROOT: ${DJANGO_STATIC_ROOT:?}
      DJANGO_ALLOWED_HOSTS: "localhost 127.0.0.1 [::1]"
      SQL_ENGINE: django.db.backends.postgresql
      SQL_DATABASE: ${POSTGRES_DB:?}
      SQL_USER: ${POSTGRES_USER:?}
      SQL_PASSWORD: ${POSTGRES_PASSWORD:?}
      SQL_HOST: db
      SQL_PORT: ${POSTGRES_PORT:-5432}
      ELASTIC_HOSTNAME: elasticsearch
      ELASTIC_PORT: ${ELASTIC_PORT:-9200}

    depends_on:
      db:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy


  nginx:
    image: nginx:1.21-perl
    container_name: coped_nginx
    volumes:
      - static_volume:${NGINX_STATIC_LOCATION:?}
      - ./configs/nginx-default.conf.template:/etc/nginx/templates/default.conf.template
    ports:
      - "1337:80"
    environment:
      STATIC_LOCATION: ${NGINX_STATIC_LOCATION:?}
    depends_on:
      - web

  db:
    image: postgres:13.4-bullseye
    container_name: coped_postgres
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - /var/lib/coped/postgresql/data:/var/lib/postgresql/data:cached
    environment:
      POSTGRES_USER: ${POSTGRES_USER:?}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?}
      POSTGRES_DB: ${POSTGRES_DB:?}

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
    container_name: coped_elastic
    volumes:
      - /var/lib/coped/elasticsearch/data:/usr/share/elasticsearch/data:cached
      - ./configs/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      ELASTIC_PASSWORD: ${ELASTICSEARCH_PASSWORD:?}
    expose:
      - 9200
      - 9300
    healthcheck:
      test: curl -s localhost:9200 > /dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 10s
      timeout: 5s
      retries: 5


  ############################
  ##  TASK RUNNER SERVICES  ##
  ############################

  tasks:
    profiles:
      - task-runner
    build: ./tasks
    container_name: coped_tasks
    environment:
      DEBUG: 0
      PYTHONPATH: /tasks  # this is where the build mounts the ./tasks directory
      # defaults
      COUCHDB_HOST: ${COUCHDB_HOST:-couch}
      COUCHDB_PORT: ${COUCHDB_PORT:-5984}
      POSTGRES_HOST: ${POSTGRES_HOST:-db}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_RESOURCE_TABLE: ${POSTGRES_RESOURCE_TABLE:-coped_resource}
      POSTGRES_TYPE_TABLE: ${POSTGRES_TYPE_TABLE:-coped_resource_type}
      # mandatory
      COUCHDB_USER: ${COUCHDB_USER:?}
      COUCHDB_PASSWORD: ${COUCHDB_PASSWORD:?}
      COUCHDB_DB: ${COUCHDB_DB:?}
      POSTGRES_USER: ${POSTGRES_USER:?}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?}
      POSTGRES_DB: ${POSTGRES_DB:?}
      ELASTICSEARCH_USER: ${ELASTICSEARCH_USER:?}
      ELASTICSEARCH_PASSWORD: ${ELASTICSEARCH_PASSWORD:?}
    depends_on:
      db:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy

volumes:
  static_volume:

configs:
  NGINX_CONFIG:
    file: ./configs/nginx-default.conf.template
  ELASTICSEARCH_CONFIG:
    file: ./configs/elasticsearch.yml
