services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile.prod
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - ./envs/prod/web
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./envs/prod/db
  nginx:
      build: ./nginx
      volumes:
        - static_volume:/home/app/web/staticfiles
      ports:
        - 1337:80
      depends_on:
        - web
  couch:
    image: couchdb:3.1
    volumes:
      - couchdb_data:/opt/couchdb/data
    expose:
      - 5984
    env_file:
      - ./envs/prod/couch

volumes:
  postgres_data:
  static_volume:
  couchdb_data:
