version: '3'

services:

  web:
    volumes:
      - ./dashboards:${VOILA_NOTEBOOK_DIR:?}
      - ./web:/app
    environment:
      DEBUG: 1

  db:
    ports:
      - "15432:5432"

  couch:
    ports:
      - "15984:5984"

  voila:
    build: ./voila
    volumes:
      - type: bind
        source: ./dashboards
        target: ${VOILA_NOTEBOOK_DIR:?}
        read_only: true
    ports:
      - "18866:8866"

  elasticsearch:
    ports:
      - "19200:9200"
      - "19300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"

  logstash:
    ports:
      - "15044:5044"
      - "15000:5000/tcp"
      - "15000:5000/udp"
      - "19600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"

  kibana:
    ports:
      - "15601:5601"
