version: '3'

services:

  web:
    volumes:
      - ./services/web:/app:cached
    environment:
      DEBUG: 1
    command: python manage.py runserver_plus 0.0.0.0:8000
    links:
      - selenium
    ports:
      - "8000:8000"

  db:
    ports:
      - "5432:5432"

  elasticsearch:
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"

  tasks:
    environment:
      DEBUG: 1
    volumes:
      - ./tasks:/tasks:cached

  selenium:
    image: selenium/standalone-firefox
    container_name: coped_selenium
    # platform: linux/amd64
    ports:
      - 4444:4444
      - 5900:5900
