version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - ./.env.prod
    depends_on:
      - frontend-db
  frontend-db:
    image: postgres:13-alpine
    volumes:
      - frontend_data:/var/lib/postgresql/data
    env_file:
      - ./.env.prod.db

volumes:
  frontend_data:
