services:

  web:
    build: ./web
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:$${DJANGO_STATIC_ROOT:?}
      - dashboards:$${VOILA_NOTEBOOK_DIR:?}
    expose:
      - 8000
    environment:
      DEBUG: 0
      SECRET_KEY: $${DJANGO_SECRET_KEY:?}
      STATIC_ROOT: $${DJANGO_STATIC_ROOT:?}
      DJANGO_ALLOWED_HOSTS: "localhost 127.0.0.1 [::1]"
      SQL_ENGINE: django.db.backends.postgresql
      SQL_DATABASE: $${POSTGRES_DB:?}
      SQL_USER: $${POSTGRES_USER:?}
      SQL_PASSWORD: $${POSTGRES_PASSWORD:?}
      SQL_HOST: db
      SQL_PORT: $${POSTGRES_PORT:-5432}
      DATABASE: $${DJANGO_DBMS_NAME:-postgres}
      ELASTIC_HOSTNAME: elasticsearch
      ELASTIC_PORT: $${ELASTIC_PORT:-9200}
    depends_on:
      - db
      - couch
      - elasticsearch

  nginx:
    build: ./nginx
    configs:
      - source: NGINX_CONFIG
        target: /etc/nginx/templates/default.conf.template
    volumes:
      - static_volume:$${NGINX_STATIC_LOCATION:?}
    ports:
      - "1337:80"
    environment:
      DASHBOARDS_ROOT: $${NGINX_DASHBOARDS_ROOT:?}
      STATIC_LOCATION: $${NGINX_STATIC_LOCATION:?}
    depends_on:
      - web
      - voila

  db:
    build: ./postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: $${POSTGRES_USER:?}
      POSTGRES_PASSWORD: $${POSTGRES_PASSWORD:?}
      POSTGRES_DB: $${POSTGRES_DB:?}

  couch:
    build: ./couchdb
    volumes:
      - couchdb_data:/opt/couchdb/data
    expose:
      - 5984
    environment:
      COUCHDB_USER: $${COUCHDB_USER:?}
      COUCHDB_PASSWORD: $${COUCHDB_PASSWORD:?}

  voila:
    build: ./voila
    volumes:
      - type: volume
        source: dashboards
        target: $${VOILA_NOTEBOOK_DIR:?}
        read_only: true
    environment:
      DASHBOARDS_ROOT: $${NGINX_DASHBOARDS_ROOT:?}
      NOTEBOOK_DIR: $${VOILA_NOTEBOOK_DIR:?}
    expose:
      - 8866

  elasticsearch:
    build: ./elasticsearch
    configs:
      - source: ELASTIC_CONFIG
        target: /usr/share/elasticsearch/config/elasticsearch.yml
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    environment:
      ELASTIC_PASSWORD: $${ELASTICSEARCH_PASSWORD:?}
    expose:
      - 9200
      - 9300

  logstash:
    build: ./logstash
    configs:
      - source: LOGSTASH_CONFIG
        target: /usr/share/logstash/config/logstash.yml
      - source: LOGSTASH_PIPELINE
        target: /usr/share/logstash/pipeline
    environment:
      ELASTIC_PASSWORD: $${ELASTICSEARCH_PASSWORD:?}
    expose:
      - 5000/tcp
      - 5000/udp
      - 5044
      - 9600
    depends_on:
      - elasticsearch

  kibana:
    build: ./kibana
    configs:
      - source: KIBANA_CONFIG
        target: /usr/share/kibana/config/kibana.yml
    environment:
      ELASTIC_PASSWORD: $${ELASTICSEARCH_PASSWORD:?}
    expose:
      - 5601
    depends_on:
      - elasticseach


volumes:
  postgres_data:
  static_volume:
  couchdb_data:
  dashboards:
  elasticsearch:


configs:
  NGINX_CONFIG:
    file: ./nginx/config/default.conf.template
  ELASTIC_CONFIG:
    file: ./elasticsearch/config/elasticsearch.yml
  LOGSTASH_CONFIG:
    file: ./logstash/config/logstash.yml
  LOGSTASH_PIPELINE:
    file: ./logstash/pipeline
  KIBANA_CONFIG:
    file: ./kibana/config/kibana.yml
