version: '3'

services:

  web:
    volumes:
      - ./services/web:/app:cached
    environment:
      DEBUG: 1
    command: python manage.py runserver_plus 0.0.0.0:8000
    links:
      - selenium
    ports:
      - "${DJANGO_DEVELOPMENT_PORT:-8000}:8000"

  db:
    ports:
      - "${POSTGRES_PORT:-5432}:5432"

  elasticsearch:
    ports:
      - "${ELASTIC_API_PORT:-9200}:9200"
      - "${ELASTIC_CLUSTER_PORT:-9300}:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"

  selenium:
    image: selenium/standalone-firefox
    container_name: coped_selenium
    # platform: linux/amd64
    ports:
      - ${SELENIUM_WEB_PORT:-4444}:4444
      - ${SELENIUM_VNC_PORT:-5900}:5900
