version: "3.9"

services:
  frontend:
    build: ./frontend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./frontend/:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - frontend-db
  frontend-db:
    image: postgres:13-alpine
    volumes:
      - frontend_data:/var/lib/postgresql/data
    env_file:
      - ./.env.dev.db

volumes:
  frontend_data:
