services:

  ##############################
  ##  DJANGO WEB APPLICATION  ##
  ##############################
  web:
    build: ./services/web
    restart: always
    container_name: ${DOCKER_CONTAINER_NAME_PREFIX:-coped}_web
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:${DJANGO_STATIC_ROOT:?}
    expose:
      - 8000
    environment:
      DEBUG: 0
      SECRET_KEY: ${DJANGO_SECRET_KEY:?}
      STATIC_ROOT: ${DJANGO_STATIC_ROOT:?}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS:-"localhost 127.0.0.1 [::1]"}
      SQL_ENGINE: django.db.backends.postgresql
      SQL_DATABASE: ${POSTGRES_DB:?}
      SQL_USER: ${POSTGRES_USER:?}
      SQL_PASSWORD: ${POSTGRES_PASSWORD:?}
      SQL_HOST: db
      SQL_PORT: ${POSTGRES_PORT:-5432}
      ELASTIC_HOSTNAME: elasticsearch
      ELASTIC_PORT: ${ELASTIC_PORT:-9200}
      RECAPTCHA_PUBLIC_KEY: ${RECAPTCHA_PUBLIC_KEY:-""}
      RECAPTCHA_PRIVATE_KEY: ${RECAPTCHA_PRIVATE_KEY:-""}
      MAILJET_API_KEY: ${MAILJET_API_KEY:-""}
      MAILJET_SECRET_KEY: ${MAILJET_SECRET_KEY:-""}
      METABASE_SUPERUSER_EMAIL: ${METABASE_SUPERUSER_EMAIL:?}
      METABASE_SUPERUSER_PASSWORD: ${METABASE_SUPERUSER_PASSWORD:?}

    depends_on:
      db:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy

  ##########################
  ## HTTP(S) PROXY SERVER ##
  ##########################
  nginx:
    image: nginx:1.21-perl
    restart: always
    container_name: ${DOCKER_CONTAINER_NAME_PREFIX:-coped}_nginx
    volumes:
      - static_volume:${NGINX_STATIC_LOCATION:?}
      - ./configs/nginx-default.conf.template:/etc/nginx/templates/default.conf.template
    ports:
      - "${NGINX_HOST_PORT:-80}:80"
    environment:
      STATIC_LOCATION: ${NGINX_STATIC_LOCATION:?}
    depends_on:
      - web

  ###################################
  ## POSTGRESQL BACKEND FOR DJANGO ##
  ###################################
  db:
    build: ./services/db
    restart: always
    container_name: ${DOCKER_CONTAINER_NAME_PREFIX:-coped}_postgres
    expose:
      - ${POSTGRES_PORT:-5432}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgresql_volume:/var/lib/postgresql/data
    user: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:?}
      POSTGRES_USER: ${POSTGRES_USER:?}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?}
      PGPORT: ${POSTGRES_PORT:-5432}

  ########################
  ## METABASE ANALYTICS ##
  ########################
  metabase:
    build: ./services/metabase
    restart: always
    container_name: ${DOCKER_CONTAINER_NAME_PREFIX:-coped}_metabase
    expose:
      - ${METABASE_PORT:-3000}
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:${METABASE_PORT:-3000}/api/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: ${MB_DB_DBNAME:-metabase}
      MB_DB_PORT: ${POSTGRES_PORT:-5432}
      MB_DB_USER: ${POSTGRES_USER:?}
      MB_DB_PASS: ${POSTGRES_PASSWORD:?}
      MB_DB_HOST: ${DOCKER_CONTAINER_NAME_PREFIX:-coped}_postgres
      MB_JETTY_PORT: ${METABASE_PORT:-3000}
      MB_JETTY_HOST: ${METABASE_HOST:-0.0.0.0}

  ###############################
  ## SEARCH BACKEND FOR DJANGO ##
  ###############################
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
    restart: always
    container_name: ${DOCKER_CONTAINER_NAME_PREFIX:-coped}_elastic
    volumes:
      - elasticsearch_volume:/usr/share/elasticsearch/data
      - ./configs/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      ELASTIC_PASSWORD: ${ELASTICSEARCH_PASSWORD:?}
    expose:
      - 9200
      - 9300
    healthcheck:
      test: curl -s localhost:9200 > /dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  static_volume: null
  postgresql_volume: null
  elasticsearch_volume: null

configs:
  NGINX_CONFIG:
    file: ./configs/nginx-default.conf.template
  ELASTICSEARCH_CONFIG:
    file: ./configs/elasticsearch.yml
