services:

  web:
    volumes:
      - ./dashboards:${VOILA_NOTEBOOK_DIR:?}

  db:
    ports:
      - "5432:5432"

  couch:
    ports:
      - "5984:5984"

  voila:
    volumes:
      - type: bind
        source: ./dashboards
        target: ${VOILA_NOTEBOOK_DIR:?}
        read_only: true
    ports:
      - "8866:8866"

  elasticsearch:
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx512m -Xms512m"

  logstash:
    ports:
      - "5044:5044"
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx512m -Xms512m"

  kibana:
    ports:
      - "5601:5601"
