version: '3'

services:

  web:
    volumes:
      - ./services/web:/app:cached
    environment:
      DEBUG: 1
      SELENIUM_HOST: ${DOCKER_CONTAINER_NAME_PREFIX:-coped}_selenium
      SELENIUM_PORT: 4444
    command: python manage.py runserver_plus 0.0.0.0:8000
    links:
      - selenium
    ports:
      - "${DJANGO_DEVELOPMENT_PORT:-8000}:8000"

  db:
    ports:
      - "${POSTGRES_PORT:-5432}:5432"

  elasticsearch:
    ports:
      - "${ELASTIC_API_PORT:-9200}:9200"
      - 9300
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"

  metabase:
    ports:
      - 3000

  selenium:
    image: selenium/standalone-firefox
    container_name: ${DOCKER_CONTAINER_NAME_PREFIX:-coped}_selenium
    # platform: linux/amd64
    ports:
      - 4444
      - 5900
