services:

  web:
    build: ./web
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - dashboards:/usr/share/voila/notebooks
    expose:
      - 8000
    environment:
      DEBUG: 0
      SECRET_KEY: ${DJANGO_SECRET_KEY:?"set a secret key"}
      DJANGO_ALLOWED_HOSTS: "localhost 127.0.0.1 [::1]"
      SQL_ENGINE: django.db.backends.postgresql
      SQL_DATABASE: ${POSTGRES_DB:?"set a database name"}
      SQL_USER: ${POSTGRES_USER:?"set a database user"}
      SQL_PASSWORD: ${POSTGRES_PASSWORD:?"set a database password"}
      SQL_HOST: db
      SQL_PORT: ${POSTGRES_PORT:-5432}
      DATABASE: ${DJANGO_DBMS_NAME:-postgres}
      ELASTIC_HOSTNAME: elasticsearch
      ELASTIC_PORT: ${ELASTIC_PORT:-9200}
    depends_on:
      - db
      - couch
      - elasticsearch

  nginx:
    image: nginx:1.21-perl
    configs:
      - source: NGINX_CONFIG
        target: /etc/nginx/conf.d/default.conf
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - "1337:80"
    depends_on:
      - web
      - voila

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:?"set a database user"}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?"set a database password"}
      POSTGRES_DB: ${POSTGRES_DB:?"set a database name"}

  couch:
    image: couchdb:3.1
    volumes:
      - couchdb_data:/opt/couchdb/data
    expose:
      - 5984
    environment:
      COUCHDB_USER: ${COUCHDB_USER:?"set a couch user"}
      COUCHDB_PASSWORD: ${COUCHDB_PASSWORD:?"set a couch password"}

  voila:
    build: ./voila
    volumes:
      - type: volume
        source: dashboards
        target: /usr/share/voila/notebooks
        read_only: true
    expose:
      - 8866

  elasticsearch:
    build: ./elasticsearch
    configs:
      - source: ELASTIC_CONFIG
        target: /usr/share/elasticsearch/config/elasticsearch.yml
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    expose:
      - 9200
      - 9300


volumes:
  postgres_data:
  static_volume:
  couchdb_data:
  dashboards:
  elasticsearch:


configs:
  NGINX_CONFIG:
    file: ./nginx/config/nginx.conf
  ELASTIC_CONFIG:
    file: ./elasticsearch/config/elasticsearch.yml

