# Generated by Django 3.2.7 on 2022-03-22 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CopedCRUDEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_json', models.JSONField()),
            ],
            options={
                'db_table': 'coped_crudevent',
            },
        ),
    ]
