# Generated by Django 3.2.7 on 2021-11-10 21:05

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(help_text='Link to more information about a resource.')),
            ],
            options={
                'db_table': 'coped_external_link',
            },
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coped_id', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='CoPED ID')),
                ('title', models.CharField(max_length=128)),
                ('about', models.TextField(blank=True, help_text='Details of eligibility, availability, application process, contacts, etc.')),
            ],
            options={
                'db_table': 'coped_fund',
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coped_id', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='CoPED ID')),
                ('name', models.CharField(max_length=128)),
                ('address', models.CharField(blank=True, help_text='The main registered address of the organisation.', max_length=128)),
                ('about', models.TextField(blank=True, help_text='Organisation overview with its role in the energy projects community.')),
            ],
            options={
                'db_table': 'coped_organisation',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coped_id', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='CoPED ID')),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('first_name', models.CharField(max_length=128)),
                ('other_name', models.CharField(blank=True, default='', max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('orcid_id', models.CharField(blank=True, default='', max_length=20)),
                ('external_links', models.ManyToManyField(to='core.ExternalLink')),
            ],
            options={
                'db_table': 'coped_person',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coped_id', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='CoPED ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, help_text='Is the project active or in some other state?', max_length=128)),
            ],
            options={
                'db_table': 'coped_project',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot', models.CharField(help_text='Name of the bot or crawler that scraped the data.', max_length=32)),
                ('url', models.URLField(help_text='Source URL of the data.', unique=True, verbose_name='URL')),
                ('json', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Raw JSON from the source', null=True, verbose_name='JSON')),
            ],
            options={
                'verbose_name_plural': 'Raw Data',
                'db_table': 'coped_raw_data',
            },
        ),
        migrations.CreateModel(
            name='ProjectPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('LEAD', 'Project Lead'), ('PARTNER', 'Project Partner or Co-Investigator'), ('PARTICIPANT', 'Other Project Participant')], default='LEAD', max_length=16)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.person')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project')),
            ],
            options={
                'verbose_name_plural': 'People',
                'db_table': 'coped_project_person',
            },
        ),
        migrations.CreateModel(
            name='ProjectOrganisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('LEAD', 'Lead Organisation'), ('PARTNER', 'Partner Organisation'), ('PARTICIPANT', 'Participant Organisation')], default='LEAD', max_length=16)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organisation')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project')),
            ],
            options={
                'db_table': 'coped_project_organisation',
            },
        ),
        migrations.CreateModel(
            name='ProjectFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Value of the funding award in GBP.', max_digits=12, null=True)),
                ('start_date', models.DateField(blank=True, help_text='Scheduled funding start date.', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Scheduled funding end date.', null=True)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fund')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project')),
            ],
            options={
                'db_table': 'coped_project_fund',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='funds',
            field=models.ManyToManyField(through='core.ProjectFund', to='core.Fund'),
        ),
        migrations.AddField(
            model_name='project',
            name='organisations',
            field=models.ManyToManyField(through='core.ProjectOrganisation', to='core.Organisation'),
        ),
        migrations.AddField(
            model_name='project',
            name='persons',
            field=models.ManyToManyField(through='core.ProjectPerson', to='core.Person'),
        ),
        migrations.AddField(
            model_name='project',
            name='raw_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.rawdata'),
        ),
        migrations.AddField(
            model_name='person',
            name='raw_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.rawdata'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='raw_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.rawdata'),
        ),
        migrations.AddField(
            model_name='fund',
            name='organisation',
            field=models.ForeignKey(blank=True, help_text='Which organisation administers this fund?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.organisation'),
        ),
        migrations.AddField(
            model_name='fund',
            name='raw_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.rawdata'),
        ),
    ]
