# Generated by Django 3.2.7 on 2021-11-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20211111_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externallink',
            name='description',
            field=models.CharField(max_length=128),
        ),
    ]
