# Generated by Django 3.2.7 on 2021-11-15 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20211111_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectfund',
            name='fund',
        ),
        migrations.AddField(
            model_name='projectfund',
            name='currency',
            field=models.CharField(default='GBP', max_length=3),
        ),
        migrations.AddField(
            model_name='projectfund',
            name='organisation',
            field=models.ForeignKey(default=16, on_delete=django.db.models.deletion.CASCADE, to='core.organisation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectfund',
            name='raw_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.rawdata'),
        ),
        migrations.AlterField(
            model_name='project',
            name='funds',
            field=models.ManyToManyField(related_name='project_funds', through='core.ProjectFund', to='core.Organisation'),
        ),
        migrations.AlterField(
            model_name='projectorganisation',
            name='role',
            field=models.CharField(default='Lead Organisation', max_length=16),
        ),
        migrations.AlterField(
            model_name='projectperson',
            name='role',
            field=models.CharField(default='Lead Person', max_length=16),
        ),
        migrations.DeleteModel(
            name='Fund',
        ),
    ]
