# Generated by Django 3.2.7 on 2021-11-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='address',
        ),
        migrations.AddField(
            model_name='organisation',
            name='addresses',
            field=models.ManyToManyField(to='core.Address'),
        ),
    ]
