# Generated by Django 3.2.7 on 2021-11-16 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20211116_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='county',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='address',
            name='line2',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='address',
            name='line3',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='address',
            name='line4',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='address',
            name='line5',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
