# Generated by Django 3.2.7 on 2021-11-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20211116_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
