# Generated by Django 3.2.7 on 2021-11-19 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(blank=True, decimal_places=12, help_text='Strength of match for the subject with this project.', max_digits=13, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject')),
            ],
            options={
                'db_table': 'coped_project_subject',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='subjects',
            field=models.ManyToManyField(through='core.ProjectSubject', to='core.Subject'),
        ),
    ]
