# Generated by Django 3.2.7 on 2021-11-20 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20211119_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externallink',
            name='link',
            field=models.URLField(help_text='Link to more information about a resource.', unique=True),
        ),
        migrations.AddConstraint(
            model_name='projectsubject',
            constraint=models.UniqueConstraint(fields=('project', 'subject'), name='subject-assigned'),
        ),
    ]
