# Generated by Django 3.2.7 on 2021-11-20 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20211120_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externallink',
            name='link',
            field=models.URLField(help_text='Link to more information about a resource.'),
        ),
    ]
