# Generated by Django 3.2.7 on 2021-11-21 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_geodata'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='geo',
            field=models.ForeignKey(blank=True, help_text='Geographic data.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.geodata'),
        ),
    ]
