# Generated by Django 3.2.7 on 2021-11-21 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_address_geo'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='geodata',
            constraint=models.UniqueConstraint(fields=('lat', 'lon'), name='unique-geo-point'),
        ),
    ]
