# Generated by Django 3.2.7 on 2021-11-05 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coped_id', models.UUIDField(default='D4BDC8F6-9C43-4A2B-BA13-220C5F4BFD4F', editable=False, verbose_name='CoPED ID')),
                ('title', models.CharField(max_length=128)),
                ('about', models.TextField(blank=True, help_text='Details of eligibility, availability, application process, contacts, etc.')),
            ],
            options={
                'db_table': 'coped_fund',
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coped_id', models.UUIDField(default='C81F4868-EAB6-4E84-8EB8-1C6E5BB87A6F', editable=False, verbose_name='CoPED ID')),
                ('name', models.CharField(max_length=128)),
                ('address', models.CharField(blank=True, help_text='The main registered address of the organisation.', max_length=128)),
                ('about', models.TextField(blank=True, help_text='Organisation overview with its role in the energy projects community.')),
            ],
            options={
                'db_table': 'coped_organisation',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coped_id', models.UUIDField(default='30926EAC-265F-4594-AD8C-3BCD83E2A213', editable=False, verbose_name='CoPED ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('about', models.TextField(blank=True, help_text='Role in the energy projects community.')),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rest_api.organisation')),
            ],
            options={
                'db_table': 'coped_person',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coped_id', models.UUIDField(default='92260465-6FFF-4804-BE80-F8998CF88184', editable=False, verbose_name='CoPED ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, help_text='Is the project active or in some other state?', max_length=128)),
            ],
            options={
                'db_table': 'coped_project',
            },
        ),
        migrations.CreateModel(
            name='ProjectPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('LEAD', 'Project Lead'), ('PARTNER', 'Project Partner or Co-Investigator'), ('PARTICIPANT', 'Other Project Participant')], default='LEAD', max_length=16)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.person')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.project')),
            ],
            options={
                'verbose_name_plural': 'People',
                'db_table': 'coped_project_person',
            },
        ),
        migrations.CreateModel(
            name='ProjectOrganisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('LEAD', 'Lead Organisation'), ('PARTNER', 'Partner Organisation'), ('PARTICIPANT', 'Participant Organisation')], default='LEAD', max_length=16)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.organisation')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.project')),
            ],
            options={
                'db_table': 'coped_project_organisation',
            },
        ),
        migrations.CreateModel(
            name='ProjectFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Value of the funding award in GBP.', max_digits=12, null=True)),
                ('start_date', models.DateField(blank=True, help_text='Scheduled funding start date.', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Scheduled funding end date.', null=True)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.fund')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.project')),
            ],
            options={
                'db_table': 'coped_project_fund',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='funds',
            field=models.ManyToManyField(through='rest_api.ProjectFund', to='rest_api.Fund'),
        ),
        migrations.AddField(
            model_name='project',
            name='organisations',
            field=models.ManyToManyField(through='rest_api.ProjectOrganisation', to='rest_api.Organisation'),
        ),
        migrations.AddField(
            model_name='project',
            name='persons',
            field=models.ManyToManyField(through='rest_api.ProjectPerson', to='rest_api.Person'),
        ),
        migrations.AddField(
            model_name='fund',
            name='organisation',
            field=models.ForeignKey(blank=True, help_text='Which organisation administers this fund?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='rest_api.organisation'),
        ),
    ]
