# Generated by Django 3.2.7 on 2021-10-26 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coped_resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='relation',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='relation',
            constraint=models.UniqueConstraint(fields=('resource_1', 'resource_2', 'relation_type'), name='unique_resources_per_relation'),
        ),
    ]
