# Generated by Django 3.2.7 on 2021-10-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coped_resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationtype',
            name='rel_link',
            field=models.CharField(blank=True, help_text="What is the label for the relation, e.g. 'PI_PER' for principal investigator (UKRI)?", max_length=32),
        ),
    ]
