# Generated by Django 3.2.7 on 2021-10-22 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coped_resources', '0002_relationtype_rel_link'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='relationtype',
            unique_together={('resource_type_1', 'resource_type_2', 'rel_link')},
        ),
    ]
