# Generated by Django 3.2.7 on 2021-11-10 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='raw_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.rawdata'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='raw_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.rawdata'),
        ),
        migrations.AddField(
            model_name='person',
            name='raw_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.rawdata'),
        ),
    ]
