# Generated by Django 3.2.7 on 2021-11-05 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='coped_id',
            field=models.UUIDField(default='C39662BC-13DB-4DD4-956B-ABD70452BF0D', editable=False, verbose_name='CoPED ID'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='coped_id',
            field=models.UUIDField(default='5A6946F0-A47E-4554-A392-F862E72E9C1C', editable=False, verbose_name='CoPED ID'),
        ),
        migrations.AlterField(
            model_name='person',
            name='coped_id',
            field=models.UUIDField(default='D5BA8B55-BCFA-4F7B-8DA6-D90756AFE7FE', editable=False, verbose_name='CoPED ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='coped_id',
            field=models.UUIDField(default='D21CE167-6037-48F7-ACCA-7D7D01DF28C9', editable=False, verbose_name='CoPED ID'),
        ),
    ]
