# Generated by Django 3.2.7 on 2021-11-30 10:57

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211130_0847'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('sender', models.UUIDField(default=uuid.uuid4)),
                ('date_requested', models.DateTimeField(default=django.utils.timezone.now)),
                ('secret', models.CharField(max_length=50)),
                ('used', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['email', 'sender', '-date_requested'],
            },
        ),
    ]
