# Generated by Django 3.2.7 on 2021-11-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211105_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='coped_id',
            field=models.UUIDField(default='bac51def-d31a-4b48-808f-40cfeb676efe', editable=False, verbose_name='CoPED ID'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='coped_id',
            field=models.UUIDField(default='4bada681-8421-477e-a868-4d57e04a7140', editable=False, verbose_name='CoPED ID'),
        ),
        migrations.AlterField(
            model_name='person',
            name='coped_id',
            field=models.UUIDField(default='c93b21f8-6a30-4393-b8e8-79f126c08b5a', editable=False, verbose_name='CoPED ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='coped_id',
            field=models.UUIDField(default='0e8da2c4-e68a-4e67-98c4-53219f5cdfe5', editable=False, verbose_name='CoPED ID'),
        ),
    ]
