# Generated by Django 3.2.7 on 2021-11-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211110_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='about',
            field=models.TextField(blank=True, help_text='Role in the energy projects community.', null=True),
        ),
    ]
