# Generated by Django 3.2.7 on 2021-11-09 19:59

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_project_raw_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rawdata',
            options={'verbose_name_plural': 'Raw Data'},
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='bot',
            field=models.CharField(blank=True, help_text='Name of the bot or crawler that scraped the data.', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='json',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Raw JSON from the source', null=True, verbose_name='JSON'),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='url',
            field=models.URLField(help_text='Source URL of the data.', verbose_name='URL'),
        ),
    ]
