# Generated by Django 3.2.7 on 2021-11-10 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211110_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='externallink',
            name='description',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
