# Generated by Django 3.2.7 on 2022-03-24 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_metabasesession_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_contributor',
            field=models.BooleanField(default=False),
        ),
    ]
