# Generated by Django 3.2.7 on 2021-11-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211106_1451'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='fund',
            name='coped_id',
            field=models.UUIDField(default='1af7f319-ec73-412c-8a0c-57ca1a797f20', editable=False, verbose_name='CoPED ID'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='coped_id',
            field=models.UUIDField(default='1ba7c341-e7fb-45b5-905a-80e276e73421', editable=False, verbose_name='CoPED ID'),
        ),
        migrations.AlterField(
            model_name='person',
            name='coped_id',
            field=models.UUIDField(default='ffec367b-6b27-478d-bb23-3909fcddc783', editable=False, verbose_name='CoPED ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='coped_id',
            field=models.UUIDField(default='22dc338e-b31f-4c48-83a1-ff9c8ae6ea86', editable=False, verbose_name='CoPED ID'),
        ),
    ]
