# Generated by Django 3.2.7 on 2021-11-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211109_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdata',
            name='bot',
            field=models.CharField(help_text='Name of the bot or crawler that scraped the data.', max_length=32),
        ),
    ]
