# Generated by Django 3.2.7 on 2021-11-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='keywords',
            field=models.ManyToManyField(to='core.Keyword'),
        ),
    ]
