# Generated by Django 3.2.7 on 2022-03-27 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220327_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='owner',
        ),
    ]
