# Generated by Django 3.2.7 on 2021-11-10 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_rawdata_bot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdata',
            name='url',
            field=models.URLField(help_text='Source URL of the data.', unique=True, verbose_name='URL'),
        ),
    ]
