# Generated by Django 3.2.7 on 2021-11-10 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_rawdata_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawdata',
            name='id',
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='url',
            field=models.URLField(help_text='Source URL of the data.', primary_key=True, serialize=False, verbose_name='URL'),
        ),
    ]
