# Generated by Django 3.2.7 on 2021-11-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_externallink_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externallink',
            name='description',
            field=models.CharField(default='External Link', max_length=128),
        ),
    ]
