# Generated by Django 3.2.7 on 2021-11-30 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_project_keywords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='keywords',
        ),
    ]
