# Generated by Django 3.2.7 on 2021-11-30 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_project_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(blank=True, decimal_places=20, help_text='Strength of match for the keyword with this project.', max_digits=21, null=True)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.keyword')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project')),
            ],
            options={
                'db_table': 'coped_project_keyword',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='keywords',
            field=models.ManyToManyField(through='core.ProjectKeyword', to='core.Keyword'),
        ),
        migrations.AddConstraint(
            model_name='projectkeyword',
            constraint=models.UniqueConstraint(fields=('project', 'keyword'), name='keyword-assigned'),
        ),
    ]
