# Generated by Django 3.2.7 on 2021-11-11 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_externallink_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='externallink',
            options={'verbose_name_plural': 'External Links'},
        ),
        migrations.AlterModelOptions(
            name='projectperson',
            options={},
        ),
        migrations.AlterField(
            model_name='projectperson',
            name='role',
            field=models.CharField(default='Project Lead', max_length=16),
        ),
    ]
