# Generated by Django 3.2.7 on 2022-03-27 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20220327_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Lock this organisation to prevent automatic updates from overwriting your changes.'),
        ),
        migrations.AddField(
            model_name='person',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Lock this person to prevent automatic updates from overwriting your changes.'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Lock this project to prevent automatic updates from overwriting your changes.'),
        ),
    ]
