# Generated by Django 3.2.7 on 2021-11-15 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20211115_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='funds',
            field=models.ManyToManyField(related_name='project_fund', through='core.ProjectFund', to='core.Organisation'),
        ),
        migrations.CreateModel(
            name='LinkedProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(default='Linked Project', max_length=32)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_project', to='core.project')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project')),
            ],
            options={
                'db_table': 'coped_linked_project',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='projects',
            field=models.ManyToManyField(through='core.LinkedProject', to='core.Project'),
        ),
    ]
