# Generated by Django 3.2.7 on 2021-11-30 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_projectkeyword_score'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='keyword',
            index=models.Index(fields=['text'], name='coped_keywo_text_06cc18_idx'),
        ),
    ]
