# Generated by Django 3.2.7 on 2021-12-01 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_keyword_coped_keywo_text_06cc18_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='Anonymous', max_length=256, verbose_name='Username'),
        ),
    ]
