# Generated by Django 3.2.7 on 2021-11-15 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20211115_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfund',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Value of the funding award.', max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='PersonOrganisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='Employee', max_length=16)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organisation')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.person')),
            ],
            options={
                'db_table': 'coped_person_organisation',
            },
        ),
        migrations.AddField(
            model_name='person',
            name='organisations',
            field=models.ManyToManyField(through='core.PersonOrganisation', to='core.Organisation'),
        ),
    ]
