# Generated by Django 3.2.7 on 2022-03-27 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_project_is_locked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Lock this project to prevent automatic updates from overwriting your changes. (You can still make changes.)'),
        ),
        migrations.AlterField(
            model_name='person',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Lock this project to prevent automatic updates from overwriting your changes. (You can still make changes.)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Lock this project to prevent automatic updates from overwriting your changes. (You can still make changes.)'),
        ),
    ]
