# Generated by Django 3.2.7 on 2021-11-16 10:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20211116_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coped_id', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='CoPED ID')),
                ('city', models.CharField(blank=True, default='', max_length=32)),
                ('country', models.CharField(blank=True, default='', max_length=32)),
                ('postcode', models.CharField(blank=True, default='', max_length=12)),
                ('region', models.CharField(blank=True, default='', max_length=32)),
                ('line1', models.CharField(blank=True, default='', max_length=32)),
            ],
            options={
                'verbose_name_plural': 'Addresses',
                'db_table': 'coped_address',
            },
        ),
    ]
