# Generated by Django 3.2.7 on 2022-04-04 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_appsetting_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='geodata',
            name='dno_id',
            field=models.SmallIntegerField(help_text='Distribution Network Operator (DNO) ID in `DNO_License_Areas_20200506.shp`', null=True),
        ),
    ]
