# Generated by Django 3.2.7 on 2021-12-05 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_user_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswChange',
        ),
    ]
