# Generated by Django 3.2.7 on 2021-12-07 12:27

from django.db import migrations
from django.contrib.postgres.operations import CreateExtension


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_delete_passwchange"),
    ]

    operations = [
        CreateExtension("postgis"),
    ]
