# Generated by Django 3.2.7 on 2022-04-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_geodata_dno_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='geodata',
            name='dno_long_name',
            field=models.CharField(blank=True, help_text='Distribution Network Operator (DNO) long name', max_length=64),
        ),
        migrations.AddField(
            model_name='geodata',
            name='dno_name',
            field=models.CharField(blank=True, help_text='Distribution Network Operator (DNO) short name', max_length=8),
        ),
        migrations.AlterField(
            model_name='geodata',
            name='dno_id',
            field=models.SmallIntegerField(help_text='Distribution Network Operator (DNO) ID from https://data.nationalgrideso.com/system/gis-boundaries-for-gb-dno-license-areas', null=True),
        ),
    ]
