# Generated by Django 3.2.7 on 2022-01-07 10:58

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_postgis_extension'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='metabase_id',
            field=models.IntegerField(editable=False, null=True, verbose_name='Metabase ID'),
        ),
    ]
