# Generated by Django 3.2.7 on 2022-01-07 12:17

import core.models.metabase_session
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20220107_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetabaseSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=40)),
                ('expires', models.DateTimeField(default=core.models.metabase_session.expiry_date_time)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'coped_metabase_session',
            },
        ),
    ]
