# Generated by Django 3.2.7 on 2022-04-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20220406_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdata',
            name='do_not_populate',
            field=models.BooleanField(default=False, help_text='Set this field if raw data should not propagate to CoPED catalogue (e.g. non-energy project).'),
        ),
    ]
