# Generated by Django 3.2.7 on 2022-04-09 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rawdata_do_not_populate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdata',
            name='do_not_populate',
            field=models.BooleanField(default=False, help_text='Set this field if raw data should not appear in CoPED catalogue (e.g. non-energy project).'),
        ),
    ]
