# Generated by Django 3.2.7 on 2022-04-09 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_rawdata_do_not_populate'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='linkedin_url',
            field=models.URLField(blank=True, verbose_name='LinkedIn URL'),
        ),
        migrations.AlterField(
            model_name='person',
            name='orcid_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ORCID iD'),
        ),
    ]
