# Generated by Django 3.2.7 on 2022-04-10 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20220409_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='geodata',
            name='ctry_code',
            field=models.CharField(blank=True, help_text='Country code', max_length=16),
        ),
        migrations.AddField(
            model_name='geodata',
            name='ctry_id',
            field=models.SmallIntegerField(help_text='Country ID from https://geoportal.statistics.gov.uk/datasets/ons::countries-december-2021-uk-buc/', null=True),
        ),
        migrations.AddField(
            model_name='geodata',
            name='ctry_name',
            field=models.CharField(blank=True, help_text='Country long name', max_length=64),
        ),
        migrations.AddField(
            model_name='geodata',
            name='ctyua_code',
            field=models.CharField(blank=True, help_text='County and Unitary Authority code', max_length=16),
        ),
        migrations.AddField(
            model_name='geodata',
            name='ctyua_id',
            field=models.SmallIntegerField(help_text='County and Unitary Authority ID from https://geoportal.statistics.gov.uk/datasets/ons::counties-and-unitary-authorities-december-2021-uk-buc/', null=True),
        ),
        migrations.AddField(
            model_name='geodata',
            name='ctyua_name',
            field=models.CharField(blank=True, help_text='County and Unitary Authority long name', max_length=64),
        ),
        migrations.AddField(
            model_name='geodata',
            name='lad_code',
            field=models.CharField(blank=True, help_text='Local Authority District (LAD) code', max_length=16),
        ),
        migrations.AddField(
            model_name='geodata',
            name='lad_id',
            field=models.SmallIntegerField(help_text='Local Authority District (LAD) ID from https://geoportal.statistics.gov.uk/datasets/ons::local-authority-districts-december-2021-uk-buc/', null=True),
        ),
        migrations.AddField(
            model_name='geodata',
            name='lad_name',
            field=models.CharField(blank=True, help_text='Local Authority District (LAD) long name', max_length=64),
        ),
    ]
