# Generated by Django 3.2.7 on 2022-01-24 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20220123_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='external_links',
            field=models.ManyToManyField(blank=True, to='core.ExternalLink'),
        ),
        migrations.AlterField(
            model_name='project',
            name='keywords',
            field=models.ManyToManyField(blank=True, through='core.ProjectKeyword', to='core.Keyword'),
        ),
        migrations.AlterField(
            model_name='project',
            name='subjects',
            field=models.ManyToManyField(blank=True, through='core.ProjectSubject', to='core.Subject'),
        ),
    ]
