# Generated by Django 3.2.7 on 2022-02-16 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20220124_0342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectfund',
            name='currency',
        ),
    ]
