# Generated by Django 3.2.7 on 2022-02-17 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        # ("easyaudit", "0016_auto_20220217_1116"),
        ("core", "0021_crudevent"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CRUDEvent",
        ),
        migrations.CreateModel(
            name="CopedCRUDEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_json", models.JSONField()),
                (
                    "easyaudit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="easyaudit.crudevent",
                    ),
                ),
            ],
            options={
                "db_table": "coped_crudevent",
            },
        ),
    ]
