# Generated by Django 3.2.7 on 2021-11-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20211116_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
