# Generated by Django 3.2.7 on 2022-04-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_organisationsubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='label',
            field=models.CharField(help_text='Short description of the subject.', max_length=128),
        ),
    ]
