# Generated by Django 3.2.7 on 2022-02-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20220217_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='funds',
            field=models.ManyToManyField(related_name='fund', through='core.ProjectFund', to='core.Organisation'),
        ),
        migrations.AlterField(
            model_name='project',
            name='organisations',
            field=models.ManyToManyField(related_name='organisation', through='core.ProjectOrganisation', to='core.Organisation'),
        ),
    ]
