# Generated by Django 3.2.7 on 2021-11-18 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20211116_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='extra_text',
            field=models.TextField(blank=True),
        ),
    ]
