# Generated by Django 3.2.7 on 2022-02-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20220217_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='persons',
            field=models.ManyToManyField(related_name='person', through='core.ProjectPerson', to='core.Person'),
        ),
    ]
