# Generated by Django 3.2.7 on 2022-02-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_project_persons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='funds',
            field=models.ManyToManyField(related_name='funded', through='core.ProjectFund', to='core.Organisation'),
        ),
        migrations.AlterField(
            model_name='project',
            name='organisations',
            field=models.ManyToManyField(through='core.ProjectOrganisation', to='core.Organisation'),
        ),
        migrations.AlterField(
            model_name='project',
            name='persons',
            field=models.ManyToManyField(through='core.ProjectPerson', to='core.Person'),
        ),
    ]
