# Generated by Django 3.2.7 on 2021-11-19 20:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_project_extra_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coped_id', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='CoPED ID')),
                ('label', models.CharField(help_text='Short description of the subject.', max_length=64)),
                ('external_link', models.ForeignKey(help_text='Link to an ontology.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.externallink')),
            ],
            options={
                'db_table': 'coped_subject',
                'ordering': ['label'],
            },
        ),
    ]
