# Generated by Django 3.2.7 on 2022-03-04 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_messages', '0002_auto_20220303_0822'),
        ('core', '0026_project_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pinax_messages.thread',),
        ),
    ]
