# Generated by Django 3.2.7 on 2022-03-07 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_projectsubscription'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectsubscription',
            unique_together={('project', 'user')},
        ),
    ]
