# Generated by Django 3.2.7 on 2022-03-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_projectsubscription_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergySearchTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'coped_energy_search_term',
            },
        ),
    ]
