# Generated by Django 3.2.7 on 2022-03-17 14:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_energysearchterm'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdata',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rawdata',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
