# Generated by Django 3.2.7 on 2022-03-17 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20220317_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='energysearchterm',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
