# Generated by Django 3.2.7 on 2022-03-17 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_subject_energy_related'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='energy_related',
            field=models.BooleanField(default=True, help_text='Is the subject related to energy projects?'),
        ),
    ]
