# Generated by Django 3.2.7 on 2022-03-17 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_appsetting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='energysearchterm',
            options={'verbose_name_plural': 'Energy Search Terms'},
        ),
    ]
