# Generated by Django 3.2.7 on 2022-03-17 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_energysearchterm_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsetting',
            name='slug',
            field=models.SlugField(default='temporary_slug', max_length=128),
            preserve_default=False,
        ),
    ]
