# Generated by Django 3.2.7 on 2021-11-03 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('address', models.CharField(blank=True, max_length=128)),
                ('about', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'coped_organisation',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('about', models.TextField(blank=True)),
                ('organisation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rest_api.organisation')),
            ],
            options={
                'db_table': 'coped_person',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('status', models.CharField(blank=True, max_length=128)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('description', models.TextField(blank=True)),
                ('funder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funder', to='rest_api.organisation')),
            ],
            options={
                'db_table': 'coped_project',
            },
        ),
        migrations.CreateModel(
            name='ProjectOrganisations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(choices=[('LEAD', 'Lead Organisation'), ('PARTNER', 'Partner Organisation'), ('PARTICIPANT', 'Participant Organisation')], default='LEAD', max_length=16)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.organisation')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='organisations',
            field=models.ManyToManyField(through='rest_api.ProjectOrganisations', to='rest_api.Organisation'),
        ),
        migrations.AddField(
            model_name='project',
            name='persons',
            field=models.ManyToManyField(to='rest_api.Person'),
        ),
    ]
