# Generated by Django 3.2.7 on 2021-11-03 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='projectorganisations',
            table='coped_project_organisations',
        ),
    ]
