# Generated by Django 3.2.7 on 2021-11-03 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_alter_projectorganisations_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectOrganisations',
            new_name='ProjectOrganisation',
        ),
        migrations.AlterModelTable(
            name='projectorganisation',
            table='coped_project_organisation',
        ),
    ]
