# Generated by Django 3.2.7 on 2021-11-03 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_auto_20211103_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(choices=[('LEAD', 'Project Lead'), ('PARTNER', 'Project Partner or Co-Investigator'), ('PARTICIPANT', 'Other Project Participant')], default='LEAD', max_length=16)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.person')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.project')),
            ],
            options={
                'db_table': 'coped_project_person',
            },
        ),
    ]
