# Generated by Django 3.2.7 on 2021-11-03 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0004_projectperson"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="funder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="funder",
                to="rest_api.organisation",
            ),
        ),
        migrations.RemoveField(model_name="project", name="persons"),
        migrations.AddField(
            model_name="project",
            name="persons",
            field=models.ManyToManyField(
                through="rest_api.ProjectPerson", to="rest_api.Person"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="title",
            field=models.CharField(max_length=256),
        ),
    ]
