# Generated by Django 3.2.7 on 2021-11-03 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0005_auto_20211103_2033'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectorganisation',
            options={'verbose_name': 'Organisation'},
        ),
        migrations.AlterModelOptions(
            name='projectperson',
            options={'verbose_name_plural': 'People'},
        ),
        migrations.RenameField(
            model_name='projectorganisation',
            old_name='relation',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='projectperson',
            old_name='relation',
            new_name='role',
        ),
    ]
