# Generated by Django 3.2.7 on 2021-11-03 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0006_auto_20211103_2043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectorganisation',
            options={},
        ),
    ]
