# Generated by Django 3.2.7 on 2021-11-03 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0007_alter_projectorganisation_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='coped_id',
            field=models.UUIDField(default='B78E90B5-0C3A-4D73-961D-6EDCA0514065'),
        ),
        migrations.AddField(
            model_name='person',
            name='coped_id',
            field=models.UUIDField(default='AB5FE71B-DD95-4C5C-87A2-8C58535CA085'),
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='coped_id',
            field=models.UUIDField(default='FDD3A0B1-E50A-4D30-9F22-A0D55DA12893'),
        ),
        migrations.AlterField(
            model_name='person',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rest_api.organisation'),
        ),
    ]
