# Basic workflow to spin up the application and test the COPED web service is responding.

name: coped-test-runner

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows the workflow to be run manually from the Actions tab
  workflow_dispatch:

jobs:
  spin-up:
    runs-on: self-hosted
    steps:
      # Check out the repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2
      - name: Start services
        run: |
          docker-compose -p coped-ci --env-file .env.ci up -d --build
          sleep 30

      - name: Test the web service responds to external requests
        run: curl -I 127.0.0.1:8983/admin/ | grep "302 Found"

      - name: Test the web service core functionality
        run: docker-compose -p coped-ci exec web python manage.py test

  spin-down:
    runs-on: self-hosted
    needs: [spin-up]
    if: always()
    steps:
      - name: Remove CI containers
        run: docker-compose -p coped-ci --env-file .env.ci down -v
