# Basic workflow to spin up the application and test the COPED web service is responding.

name: coped-test-runner

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows the workflow to be run manually from the Actions tab
  workflow_dispatch:

jobs:
  spin-up:
    runs-on: self-hosted
    steps:
      # Check out the repository under $GITHUB_WORKSPACE
      - name: Checkout repo and download LFS dependencies
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout
      - name: Start services
        run: |
          docker-compose -p coped-ci --env-file .env.ci up -d --build
          sleep 30

      - name: Test CoPED core functionality
        run: docker-compose -p coped-ci exec web python manage.py test --noinput

  spin-down:
    runs-on: self-hosted
    needs: [spin-up]
    if: always()
    steps:
      - name: Remove CI containers
        run: docker-compose -p coped-ci --env-file .env.ci down -v
