# Basic workflow to spin up the application and test the COPED web service is responding.

name: coped-test-runner

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows the workflow to be run manually from the Actions tab
  workflow_dispatch:

jobs:
  spin-up:
    runs-on: self-hosted
    steps:
      # Check out the repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      - name: Set docker project name
        run: echo "COMPOSE_PROJECT_NAME=coped-ci-`date +%s`" >> $GITHUB_ENV

      - name: Start services
        run: |
          cp .env.example .env.ci
          docker-compose -p "${{ env.COMPOSE_PROJECT_NAME }}" --env-file .env.ci --file docker-compose.yaml --file docker-compose.ci.yaml up -d --build
          sleep 30

      - name: Test the web frontend responds to requests
        run: curl -I http://127.0.0.1:1337/admin/ | grep "302 Found"

      - name: Tidy up
        run: docker-compose -p "${{ env.COMPOSE_PROJECT_NAME }}" --env-file .env.ci down -v
