# Basic workflow to spin up the application and test the COPED web service is responding.

name: coped-test-runner

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows the workflow to be run manually from the Actions tab
  workflow_dispatch:

jobs:
  spin-up:
    runs-on: self-hosted
    env:
      DATE: ${{ echo `date +%s` }} # unique-ish timestamp
    steps:
      # Check out the repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      - name: Copy over environment variables for "production"
        run: cp .env.example .env.prod

      - name: Build the application
        run: docker-compose build

      - name: Launch the application services
        run: COMPOSE_PROJECT_NAME=coped-ci-${DATE} docker-compose --env-file .env.prod up -d

      - name: Wait for the services to settle down
        run: sleep 30

      - name: Test the web frontend is responding to requests
        run: curl -I http://localhost:1337/admin/ | grep "302 Found"

      - name: Ask docker-compose to clean up
        run: COMPOSE_PROJECT_NAME=coped-ci-${DATE} docker-compose down
